config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get "events/index"
  root to: "events#index"

  resources :events
  resources :users, only: [:show]
  resources :attendees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendees, foreign_key: 'attended_event_id'
  has_many :users, through: :attendees, source: :attendee

  scope :past, -> { where("date < date('now')") }
  scope :upcoming, -> { where("date >= date('now')") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendees, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendees, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    puts params.inspect
    @attendee = Attendee.create!(attendee_params)

    if @attendee.save
      redirect_to root_path, notice: 'You are now attending this event.'
    else
      puts @attendee.errors.full_messages  # This will print errors to your server log
      redirect_to events_path, alert: "Unable to attend this event: #{@attendee.errors.full_messages.join(', ')}"
    end
  end

  private
  def attendee_params
    params.permit(:attendee_id, :attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events_past = Event.past.all.order(created_at: :desc)
    @events_upcoming = Event.upcoming.all.order(created_at: :desc)
  end

  def new
    @event = current_user.created_events.new
  end

  def show
    @event = Event.find(show_params[:id])
    @attendees = @event.users
  end

  def create
    @event = current_user.created_events.new(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :date, :location)
  end

  def show_params
    params.permit(:id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @events = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Welcome to Eventbrite!</h1>
<% if user_signed_in? %>
    <%= button_to "My Profile", user_path(current_user), method: :get %>
    <br>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= button_to "Sign In", new_user_session_path, method: :get %>
<% end %>

<br>
<br>

<h2>Upcoming Events</h2>

<% @events_upcoming.each do |event| %>
    <ul>
        <li>
            <%= link_to event.name, event_path(event), method: :get %> 
            <% if user_signed_in? and !Attendee.where(attendee_id: current_user.id).where(attended_event_id: event.id).exists? %>
                <%= button_to "Attend Event", attendees_path, method: :post, params: { attendee_id: current_user.id, attended_event_id: event.id } %>
            <% end %>
        </li>
    </ul>
<% end %>

<br>
<br>

<h2>Past Events</h2>

<% @events_past.each do |event| %>
    <ul>
        <li>
            <%= link_to event.name, event_path(event), method: :get %> 
            <% if user_signed_in? and !Attendee.where(attendee_id: current_user.id).where(attended_event_id: event.id).exists? %>
                <%= button_to "Attend Event", attendees_path, method: :post, params: { attendee_id: current_user.id, attended_event_id: event.id } %>
            <% end %>
        </li>
    </ul>
<% end %>

app/views/events/new.html.erb
<%= form_with(model: @event) do |form| %>
    <%= form.label(:name, "")%>
    <%= form.text_field(:name) %>
    <%= form.label(:date, "")%>
    <%= form.date_field(:date) %>
    <%= form.label(:location, "")%>
    <%= form.text_field(:location) %>
    <%= form.submit("Create!") %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %> Attendees</h1>

<ul>
    <% @attendees.each do |attendee| %>
        <li><%= attendee.email %></li>
    <% end %>
<ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.email %>!</h1>
<h2>Here are your created events</h2>

<br>
<br>
<%= link_to "Create an Event", new_event_path, method: :get %>
<br>
<br>

<h2>Created events</h2>
<ul>
    <% @user.created_events.all.each do |event| %>
        <li><%= event.name %></li>
    <% end %>
</ul>

<br>
<br>

<h2>Upcoming events</h2>
<ul>
    <% @events.where("date >=  date('now')").all.each do |event| %>
        <li><%= event.name %></li>
    <% end %>
</ul>

<br>
<br>

<h2>Attended events</h2>
<ul>
    <% @events.where("date <  date('now')").all.each do |event| %>
        <li><%= event.name %></li>
    <% end %>
</ul>